# TGDL 產品環境配置模板
# 用途：產品版本的配置，支援多使用者訪問
# Port: 5001

# ==================== Telegram API 設定 ====================
# 從 https://my.telegram.org/apps 獲取
api_hash: YOUR_API_HASH_HERE
api_id: YOUR_API_ID_HERE

# ==================== Bot 設定（可選）====================
# 如需 Bot 通知功能，填入 Bot Token
bot_token: YOUR_BOT_TOKEN_HERE

# ==================== Web 介面設定 ====================
web_port: 5001  # 產品版本 Port

# ==================== 下載路徑設定 ====================
save_path: TGDL/unified_downloads

# ==================== Bot 權限設定（可選）====================
# 限制哪些 Telegram User ID 可以使用 Bot 命令
allowed_user_ids:
  - YOUR_TELEGRAM_USER_ID_HERE

# ==================== 基本下載設定 ====================
media_types:
  - photo
  - video
  - document
  - audio

language: EN

# ==================== 環境標識 ====================
# Environment: Production
# Port: 5001
# Access: https://your-domain.com (透過 Cloudflare Tunnel)
